create table users
(
    user_id   integer generated by default as identity
        primary key,
    login     varchar(50)  not null
        constraint unique_login
            unique,
    password  varchar(50)  not null,
    full_name varchar(100) not null,
    birthday  date         not null
);

alter table users
    owner to anpoliakov;

create table phone_numbers
(
    phone_number_id bigint generated by default as identity
        primary key,
    user_id         integer     not null
        references users
            on delete cascade,
    phone_number    varchar(20) not null
        unique
);

alter table phone_numbers
    owner to anpoliakov;

create table emails
(
    email_id bigint generated by default as identity
        primary key,
    user_id  integer     not null
        references users
            on delete cascade,
    email    varchar(50) not null
        unique
);

alter table emails
    owner to anpoliakov;

create table accounts
(
    account_id integer generated by default as identity
        constraint account_pkey
            primary key,
    user_id    integer        not null
        constraint account_user_id_fkey
            references users
            on delete set null,
    balance    numeric(19, 2) not null
        constraint account_balance_check
            check (balance >= (0)::numeric)
);

alter table accounts
    owner to anpoliakov;

create table refresh_tokens
(
    token_id integer generated by default as identity
        primary key,
    user_id  integer      not null
        unique
        references users
            on delete cascade,
    token    varchar(200) not null
);

alter table refresh_tokens
    owner to anpoliakov;

