create sequence account_account_id_seq;

create table users
(
    user_id         integer generated by default as identity
        primary key,
    login           varchar(50)    not null
        constraint unique_login
            unique,
    password        varchar(60)    not null,
    full_name       varchar(100)   not null,
    birthday        date           not null,
    initial_deposit numeric(19, 2) not null
);

create table phone_numbers
(
    phone_number_id bigint generated by default as identity
        primary key,
    user_id         integer     not null
        references users
            on delete cascade,
    phone_number    varchar(20) not null
        unique
);

create table emails
(
    email_id bigint generated by default as identity
        primary key,
    user_id  integer     not null
        references users
            on delete cascade,
    email    varchar(50) not null
        unique
);

create table accounts
(
    account_id integer generated by default as identity
        constraint account_pkey
            primary key,
    user_id    integer        not null
        constraint account_user_id_fkey
            references users
            on delete set null,
    balance    numeric(19, 2) not null
        constraint account_balance_check
            check (balance >= (0)::numeric)
);

alter sequence account_account_id_seq owned by accounts.account_id;

create table refresh_tokens
(
    token_id integer generated by default as identity
        primary key,
    user_id  integer      not null
        unique
        references users
            on delete cascade,
    token    varchar(200) not null
);


