create table emails
(
    email_id bigint generated by default as identity
        primary key,
    user_id  integer     not null
        references users
            on delete cascade,
    email    varchar(50) not null
        unique
);

alter table emails
    owner to anpoliakov;

