create table phone_numbers
(
    phone_number_id bigint generated by default as identity
        primary key,
    user_id         integer     not null
        references users
            on delete cascade,
    phone_number    varchar(20) not null
        unique
);

alter table phone_numbers
    owner to anpoliakov;

