create table refresh_tokens
(
    token_id integer generated by default as identity
        primary key,
    user_id  integer      not null
        unique
        references users
            on delete cascade,
    token    varchar(200) not null
);

alter table refresh_tokens
    owner to anpoliakov;

