create table users
(
    user_id         integer generated by default as identity
        primary key,
    login           varchar(50)    not null
        constraint unique_login
            unique,
    password        varchar(60)    not null,
    full_name       varchar(100)   not null,
    birthday        date           not null,
    initial_deposit numeric(19, 2) not null
);

alter table users
    owner to anpoliakov;

